In [2]:
import pandas as pd
import numpy as np

C:\Users\pa389\AppData\Local\Temp\ipykernel_16376\2162656668.py:1: DeprecationWarning: 
Pyarrow will become a required dependency of pandas in the next major release of pandas (pandas 3.0),
(to allow more performant data types, such as the Arrow string type, and better interoperability with other libraries)
but was not found to be installed on your system.
If this would cause problems for you,
please provide us feedback at https://github.com/pandas-dev/pandas/issues/54466
        
  import pandas as pd


In [3]:
df = pd.read_csv("homeprices.csv")
df.head()

town  area   price
0  monroe township  2600  550000
1  monroe township  3000  565000
2  monroe township  3200  610000
3  monroe township  3600  680000
4  monroe township  4000  725000

In [34]:
dummy = pd.get_dummies(df.town)
dummy

#here we are doing the one hot encoding and giving the value to the nominal data

monroe township  robinsville  west windsor
0              True        False         False
1              True        False         False
2              True        False         False
3              True        False         False
4              True        False         False
5             False        False          True
6             False        False          True
7             False        False          True
8             False        False          True
9             False         True         False
10            False         True         False
11            False         True         False
12            False         True         False

In [12]:
merge = pd.concat([df,dummy],axis = 'columns')
merge

#Here we are merging the original table to the encoded table;

town  area   price  monroe township  robinsville  west windsor
0   monroe township  2600  550000             True        False         False
1   monroe township  3000  565000             True        False         False
2   monroe township  3200  610000             True        False         False
3   monroe township  3600  680000             True        False         False
4   monroe township  4000  725000             True        False         False
5      west windsor  2600  585000            False        False          True
6      west windsor  2800  615000            False        False          True
7      west windsor  3300  650000            False        False          True
8      west windsor  3600  710000            False        False          True
9       robinsville  2600  575000            False         True         False
10      robinsville  2900  600000            False         True         False
11      robinsville  3100  620000            False         True         False
12      robinsville  3600  695000            False         True         False

In [16]:
final = merge.drop(['town','west windsor'],axis = 'columns')
final

#Here we are removing\Droping the unwanted columns

area   price  monroe township  robinsville
0   2600  550000             True        False
1   3000  565000             True        False
2   3200  610000             True        False
3   3600  680000             True        False
4   4000  725000             True        False
5   2600  585000            False        False
6   2800  615000            False        False
7   3300  650000            False        False
8   3600  710000            False        False
9   2600  575000            False         True
10  2900  600000            False         True
11  3100  620000            False         True
12  3600  695000            False         True

In [19]:
from sklearn.linear_model  import LinearRegression
r = LinearRegression()

In [20]:
#provide the X and Y for the prediction;

X = final.drop(['price'],axis = 'columns')
X

area  monroe township  robinsville
0   2600             True        False
1   3000             True        False
2   3200             True        False
3   3600             True        False
4   4000             True        False
5   2600            False        False
6   2800            False        False
7   3300            False        False
8   3600            False        False
9   2600            False         True
10  2900            False         True
11  3100            False         True
12  3600            False         True

In [22]:
# Y = price because the price is the independent variable it will depend on the other factors

Y = final.price
Y

0     550000
1     565000
2     610000
3     680000
4     725000
5     585000
6     615000
7     650000
8     710000
9     575000
10    600000
11    620000
12    695000
Name: price, dtype: int64

In [24]:
# Train the model

r.fit(X,Y)

LinearRegression()

In [54]:
r.predict([[1,0,2800]])

c:\Python312\Lib\site-packages\sklearn\base.py:493: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


ValueError: X has 3 features, but LinearRegression is expecting 4 features as input.

#Excercise


In [40]:
df1 = pd.read_csv('carprices.csv')
df1.head()

Car Model  Mileage  Sell Price($)  Age(yrs)
0    BMW X5    69000          18000         6
1    BMW X5    35000          34000         3
2    BMW X5    57000          26100         5
3    BMW X5    22500          40000         2
4    BMW X5    46000          31500         4

In [42]:
dummy1 = pd.get_dummies(df1['Car Model'])
dummy1

Audi A5  BMW X5  Mercedez Benz C class
0     False    True                  False
1     False    True                  False
2     False    True                  False
3     False    True                  False
4     False    True                  False
5      True   False                  False
6      True   False                  False
7      True   False                  False
8      True   False                  False
9     False   False                   True
10    False   False                   True
11    False   False                   True
12    False   False                   True

In [43]:
merge1 = pd.concat([dff,dummy1],axis='columns')
merge1

Car Model  Mileage  Sell Price($)  Age(yrs)  Audi A5  BMW X5  \
0                  BMW X5    69000          18000         6    False    True   
1                  BMW X5    35000          34000         3    False    True   
2                  BMW X5    57000          26100         5    False    True   
3                  BMW X5    22500          40000         2    False    True   
4                  BMW X5    46000          31500         4    False    True   
5                 Audi A5    59000          29400         5     True   False   
6                 Audi A5    52000          32000         5     True   False   
7                 Audi A5    72000          19300         6     True   False   
8                 Audi A5    91000          12000         8     True   False   
9   Mercedez Benz C class    67000          22000         6    False   False   
10  Mercedez Benz C class    83000          20000         7    False   False   
11  Mercedez Benz C class    79000          21000         7    False   False   
12  Mercedez Benz C class    59000          33000         5    False   False   

    Mercedez Benz C class  
0                   False  
1                   False  
2                   False  
3                   False  
4                   False  
5                   False  
6                   False  
7                   False  
8                   False  
9                    True  
10                   True  
11                   True  
12                   True

In [46]:
final = merge1.drop(['Car Model','Mercedez Benz C class'],axis = 'columns')
final


Mileage  Sell Price($)  Age(yrs)  Audi A5  BMW X5
0     69000          18000         6    False    True
1     35000          34000         3    False    True
2     57000          26100         5    False    True
3     22500          40000         2    False    True
4     46000          31500         4    False    True
5     59000          29400         5     True   False
6     52000          32000         5     True   False
7     72000          19300         6     True   False
8     91000          12000         8     True   False
9     67000          22000         6    False   False
10    83000          20000         7    False   False
11    79000          21000         7    False   False
12    59000          33000         5    False   False

In [47]:
x = final.drop(['Sell Price($)'],axis = 'columns')
x

Mileage  Age(yrs)  Audi A5  BMW X5
0     69000         6    False    True
1     35000         3    False    True
2     57000         5    False    True
3     22500         2    False    True
4     46000         4    False    True
5     59000         5     True   False
6     52000         5     True   False
7     72000         6     True   False
8     91000         8     True   False
9     67000         6    False   False
10    83000         7    False   False
11    79000         7    False   False
12    59000         5    False   False

In [49]:
y = final['Sell Price($)']
y

0     18000
1     34000
2     26100
3     40000
4     31500
5     29400
6     32000
7     19300
8     12000
9     22000
10    20000
11    21000
12    33000
Name: Sell Price($), dtype: int64

In [56]:
obj = LinearRegression()

In [57]:
obj.fit(x,y)

LinearRegression()

In [58]:
obj.predict([[45000,4,0,0]])

c:\Python312\Lib\site-packages\sklearn\base.py:493: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([36991.31721061])

In [59]:
obj.predict([[86000,7,0,1]])

c:\Python312\Lib\site-packages\sklearn\base.py:493: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([11080.74313219])

In [61]:
obj.score(x,y)

0.9417050937281082

In [72]:
obj.predict([[10000,7,0,1]])

c:\Python312\Lib\site-packages\sklearn\base.py:493: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([39210.02230571])